support read github file raw content
np-guard/baseline-rules pull request #10
Opened 2022-03-21 13:01 UTC by shireenf-ibm

I made a change in an existing test, hoping it is okay

2022-03-21 14:30 UTC, zivnevo requested changes
a few minor comments

2022-03-22 08:37 UTC, shireenf-ibm commented on src/baseline_rule.py
> +from urllib.request import urlopen
Right

2022-03-22 08:41 UTC, shireenf-ibm commented on tests/testBaselineRuleToNetPol.py
> +    return f'https://raw.githubusercontent.com/np-guard/baseline-rules/master/examples/{rule_name}.yaml'
We have the same method with non-raw urls in the testBaselineRuleToGlobalNetPol.py test file.

2022-03-22 08:56 UTC, zivnevo commented on tests/testBaselineRuleToNetPol.py
> +    return f'https://raw.githubusercontent.com/np-guard/baseline-rules/master/examples/{rule_name}.yaml'
Ah sorry, I forgot about the new `testBaselineRuleToGlobalNetPol.py`.
It's ok then.

2022-03-22 08:58 UTC, zivnevo approved these changes
ok

2022-03-22 09:38 UTC, merged